name: Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ./package/dist
          key: 'dist'
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: '7.29.0'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build:package

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ./package/dist
          key: 'dist'
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: '7.29.0'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/
      - run: cd ./package
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
